### ISSUE TITLE
New project: No element available

### ISSUE THREAD

**Issue by jboelaert** [emilienschultz/activetigger#101]
After creating a project and computing features, in annotation tab I get "No element available" in the tagging field

Before computing visualization, I get two error popups:
"Projection model doesn't exist for this user"
"Element does not exist."

After computing visualization, I get these two:
"Simplemodel doesn't exist"
"Element does not exist."

Errors are the same with or without having created labels.

**Comment by emilienschultz** [comment]
Ok, thanks; I thought they were gone, I need to fix this
