### ISSUE TITLE
Add Confirmation Messages for Actions or Errors When Data/Features Are Missing

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#112]
In certain areas, provide confirmation messages to indicate whether an action has been successfully processed or if there is an error or missing data. Examples:
- Export annotation test data button should give feedback when no test data is available ?
- Provide confirmation or warning messages when models lack features in the prediction and visualization sections of the annotation module ?

**Comment by emilienschultz** [comment]
Right. Done.
