### ISSUE TITLE
User Access and Deletion Permissions

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#114]
It looks like I can delete others accounts in the "Manage users and rights" section. I haven't tried performing the deletion, so there may already be a security measure in place. Is this behavior tied to the beta-test conditions or linked to the privileges of a manager role?

**Comment by emilienschultz** [comment]
Perfectly right. Good catch. I modified and now people can only see account they created. Only root can access all account.

**Comment by emilienschultz** [comment]
Crap. No, people need to see other accounts. I made the wrong fix :)

**Comment by emilienschultz** [comment]
Ok, you can see all the account but only delete those you have created, except you are root
