### ISSUE TITLE
Inconsistent Selection Formats for Dataset Creation Parameters

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#115]
When creating a dataset, the parameters "Id column (they need to be unique)" and "Column for existing annotations (optional)" use a different selection format compared to "Text column" and "Contextual information columns."
The former parameters provide a simple dropdown menu, while the latter allow for a select input with text entry to narrow matches.
Is this intentional and due to the fact that "Id" and "Column for existing annotations" only accept a single column, whereas the others can take multiple columns?

**Comment by emilienschultz** [comment]
Yes, this is the reason. Is it disturbing ?

**Comment by leomignot** [comment]
No, I think it's fine like this.
