### ISSUE TITLE
Add Ability to Reorder Labels ?

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#118]
Providing a way to reorder labels would facilitate faster and more efficient selection (for example if users want to reassign keyboard shortcuts or place frequently used labels at the top).

**Comment by emilienschultz** [comment]
Nice idea, I will look how to do it

**Comment by emilienschultz** [comment]
I added this feature, thanks (for the moment, it is not recorded if you change page, but it is a start). Tell me if you like it.
