### ISSUE TITLE
Issue with 'Convert Label' Functionality

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#119]
I'm encountering an issue with the "Convert Label" functionality and I'm not sure if it's a bug or if I'm missing something in its usage. I get the following error message:

`[{"type":"enum","loc":["path","action"],"msg":"Input should be 'delete', 'add' or 'update'","input":"rename","ctx":{"expected":"'delete', 'add' or 'update'"}},{"type":"missing","loc":["query","label"],"msg":"Field required","input":null}]`

**Comment by emilienschultz** [comment]
Error in the API. Thanks :)
