### ISSUE TITLE
Option to skip text without annotating ?

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#122]
Maybe have the possibility to skip to another text without annotating the current one? This could improve workflow when a text does not require annotation or needs to be deferred. (might be painfull with features like maxprob selection?)

Use case : Maybe I've missed it, but for example, what should a user do if a text does not match the labels he's interested in? He might want to leave a text blank if it's not relevant to the tags. (But from your side I suppose it's a pain because you end up with untagged="hasn't been seen yet" and untagged="it's processed and I don't want a tag"). In this case, the best approach would be for the user to create a specific “neutral” label if he needs one?
(Maybe I'm just missing something)

**Comment by emilienschultz** [comment]
I don't think there is a need to avoid elements, and yes maybe it has to be dealt with a specific HS tag. But is it to the user to create it or do we design a button for that @eollion @jboelaert. Maybe we can add the possibility to delete from the trainset specific labels ?

**Comment by emilienschultz** [comment]
After discussion, I think it is better not to add a skip button, since other solutions (explore, the map, or adding a HS category) is possible
