### ISSUE TITLE
Display previously chosen tags (in annotate)?

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#123]
When navigating back to previously annotated texts (from the arrow next to the tag or by making a random selection on tagged), the selected tag should probably be displayed ? or it should indicate that the text has already been tagged ?
I also think that going back with the arrow without retagging mess around with your untagged accounts. I'll make another issue for that.

**Comment by emilienschultz** [comment]
You can display the complete history with the display option. But you're right there is a need to indicate somewhere the element has already been tagged. I do that

The way back button works seem fine : if you go back, you don't erase the previous tag (that's the reason the counter doesn't change) but you can retag it.
