### ISSUE TITLE
Annotated counts going crazy

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#126]
I think the values in the annotated count display (e.g., "XX / YY / ZZ") behave inconsistently, especially when changing categories and navigating back to previous texts.
It seems that when you navigate backwards using the arrow, the number of untagged tags sometimes increments (incorrectly, as I think you keep the original tag even if you don't choose a new one...). I think I also manage to mess around with the count of tagged texts. 
Closing and reopening the session seems to reset most of the counts to their correct values (but not everything, there is still a count error in my test project if you want to check)

Ways to reproduce : I don't really know, but going back to previous texts with the arrow next to the tags is probably the culprit (honestly, I was just trying to break stuff).

**Comment by emilienschultz** [comment]
I don't see the problem anymore. Please reopen if you find it again
