### ISSUE TITLE
Test mode & "explore the test set"

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#128]
In test mode, explore section displays the train set (and not the test set ?)
Cf. in the description it is indicated that :
"Once activated, the test mode :
- Deactivate for the user the choice of scheme, label management
- Allow only annotation for the test set
- Allow to explore the test set"
The explore section currently shows the train set instead of the test set, which might be inconsistent with the intended behavior.

**Comment by emilienschultz** [comment]
How yeah, bug big. Fixed in the next version
