### ISSUE TITLE
Contextual "Refetch element with current selection" option not working

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#129]
I think the "Refetch element with current selection" does not respond to parameter changes after error.
When an error occurs and parameters are modified, "Refetch Element with current selection" button does not appear to consider the changes; it continues to display the error. However, using the top-level Refetch Element works correctly after modifications.
Steps to reproduce the issue :  Deliberately create an error by fetching something impossible > Error > Change parameters to possible ones and click on the contextual button > Error > Click on the top level "Refetch element" > OK

**Comment by emilienschultz** [comment]
I made a change, hopefully it solves this problem
