### ISSUE TITLE
Visualization xlim and ylim

### ISSUE THREAD

**Issue by jboelaert** [emilienschultz/activetigger#130]
The visualization xlim and ylim should be a bit larger, right now it looks cut at the edges (some obs not appearing?)

![Screenshot from 2024-11-13 14-33-25](https://github.com/user-attachments/assets/3910340e-e06e-42e0-a29b-2e8cfba278a2)

**Comment by emilienschultz** [comment]
I made a fix, but i still have bug on the zoom (it jumps from -1.5/1.5 to -1/1)
