### ISSUE TITLE
Regex and case sensitivity 

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/activetigger#138]
It seems that the Regex are case sensitive. If this is an intentional choice, perhaps consider adding a warning? Many "typical" users may not be aware of this, as many interfaces do not differentiate based on case. Even "advanced" users might run into issues if they don't immediately realize it (definitely not speaking from experience…).

**Comment by emilienschultz** [comment]
Yes it was inconsistant. It is fixed. Since it is "real" regex, for the moment I keep case sensitivity. I add this point in the doc. but it can be discussed in the future (@eollion)
