### ISSUE TITLE
Behavior when duplicated id variable

### ISSUE THREAD

**Issue by jboelaert** [emilienschultz/activetigger#154]
When a project is created with duplicated id variable, 
1 - the project is still created, it should throw an error at import time instead
2 - the id shown in Explore is not the one found in the data

**Comment by emilienschultz** [comment]
Yes, there is a rule for the moment : if the index column is not a real index (unique identifier), the row number is used instead.   I can explicitely indicate it. I prefer do this way to avoid to reject the project, and allow the creation... Is it a problem N

**Comment by jboelaert** [comment]
Yes, I think it is a bit misleading. I would say the way to go is to solve issue #155 : add the option to import without id column, and throw an error if the selected column has duplicates.

**Comment by emilienschultz** [comment]
Agreed. I did the modification.
