### ISSUE TITLE
Error building fasttext on install

### ISSUE THREAD

**Issue by JbIPS** [emilienschultz/activetigger#171]
Hi,

I'm trying to install the project with Python 3.11 and `pip install -r api/requirements.txt` but the process throw an error on `fasttext` package
<summary>Stack trace</summary>
<details>
    Building wheels for collected packages: fasttext
      Building wheel for fasttext (pyproject.toml) ... error
      error: subprocess-exited-with-error
    
      × Building wheel for fasttext (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [46 lines of output]
          /tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/setuptools/dist.py:488: SetuptoolsDeprecationWarning: Invalid dash-separated options
          !!
    
          ********************************************************************************
          Usage of dash-separated 'description-file' will not be supported in future
          versions. Please use the underscore name 'description_file' instead.
    
          By 2025-Mar-03, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.
    
          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************
    
          !!
            opt = self.warn_dash_deprecation(opt, section)
          running bdist_wheel
          running build
          running build_py
          creating build/lib.linux-x86_64-cpython-311/fasttext
          copying python/fasttext_module/fasttext/FastText.py -> build/lib.linux-x86_64-cpython-311/fasttext
          copying python/fasttext_module/fasttext/__init__.py -> build/lib.linux-x86_64-cpython-311/fasttext
          creating build/lib.linux-x86_64-cpython-311/fasttext/util
          copying python/fasttext_module/fasttext/util/__init__.py -> build/lib.linux-x86_64-cpython-311/fasttext/util
          copying python/fasttext_module/fasttext/util/util.py -> build/lib.linux-x86_64-cpython-311/fasttext/util
          creating build/lib.linux-x86_64-cpython-311/fasttext/tests
          copying python/fasttext_module/fasttext/tests/__init__.py -> build/lib.linux-x86_64-cpython-311/fasttext/tests
          copying python/fasttext_module/fasttext/tests/test_configurations.py -> build/lib.linux-x86_64-cpython-311/fasttext/tests
          copying python/fasttext_module/fasttext/tests/test_script.py -> build/lib.linux-x86_64-cpython-311/fasttext/tests
          running build_ext
          creating tmp
          g++ -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -I/home/jbrichardet/workspace/activetigger/venv/include -I/usr/include/python3.11 -c /tmp/tmpppwf3aex.cpp -o tmp/tmpppwf3aex.o -std=c++17
          g++ -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -I/home/jbrichardet/workspace/activetigger/venv/include -I/usr/include/python3.11 -c /tmp/tmplesprzn5.cpp -o tmp/tmplesprzn5.o -fvisibility=hidden
          building 'fasttext_pybind' extension
          creating build/temp.linux-x86_64-cpython-311/python/fasttext_module/fasttext/pybind
          creating build/temp.linux-x86_64-cpython-311/src
          g++ -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -I/tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/pybind11/include -I/tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/pybind11/include -Isrc -I/home/jbrichardet/workspace/activetigger/venv/include -I/usr/include/python3.11 -c python/fasttext_module/fasttext/pybind/fasttext_pybind.cc -o build/temp.linux-x86_64-cpython-311/python/fasttext_module/fasttext/pybind/fasttext_pybind.o -DVERSION_INFO=\"0.9.3\" -std=c++17 -fvisibility=hidden
          In file included from /tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/attr.h:13,
                           from /tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/detail/class.h:12,
                           from /tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:12,
                           from /tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/numpy.h:12,
                           from python/fasttext_module/fasttext/pybind/fasttext_pybind.cc:13:
          /tmp/pip-build-env-8o0hkw3v/overlay/lib/python3.11/site-packages/pybind11/include/pybind11/detail/common.h:274:10: fatal error: Python.h: No such file or directory
            274 | #include <Python.h>
                |          ^~~~~~~~~~
          compilation terminated.
          error: command '/usr/bin/g++' failed with exit code 1
</details>

I saw that `fasttext` dependency points to the repo's main branch, is there a specific commit needed and not published on PyPi? If so, which one? 

## Env
OS: Fedora 41
Python version: 3.11.11

**Comment by emilienschultz** [comment]
I don't remember why I added the repo and not the pypi. I will need to investigate. 

I don't know why you have an error for fasttext though. Python.h seems to be a Python basic depency (https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory). 

fasttext is not absolutely necessary. So you can comment it and continue the install without it. I will make some attempts.

**Comment by JbIPS** [comment]
You're right, it **is a basic dependency** if you install the `*-devel` package! Since I downgrade my python to 3.11, I forgot to install the dev package associated.

Install issue is solved but it could be good to make a proper dependcy for `fasttext`.
