### ISSUE TITLE
get_hash implementation likely incorrect.

### ISSUE THREAD

**Issue by Carreau** [emilienschultz/activetigger#176]
In https://github.com/emilienschultz/activetigger/blob/ec47c5f2467d8d437e38224d2d1e8f7998861d38/api/activetigger/functions.py#L78-L84

get_hash is likely incorrect;  it generate the salt while calculating the hash, which create a new hash each time:

```
In [3]: salt = bcrypt.gensalt()
   ...: hashed = bcrypt.hashpw('same'.encode(), salt)
   ...: hashed
Out[3]: b'$2b$12$D19WSwdJLQ2SSKxVJxR7fOj3qMWP.wmF9/cPOBUmfDbIhZaUoBQd6'

In [4]: salt = bcrypt.gensalt()
   ...: hashed = bcrypt.hashpw('same'.encode(), salt)
   ...: hashed
Out[4]: b'$2b$12$BPFt4DnwwACtws9X13ru8uVsupijjUFnjMnvfB05wka14M/nVxB86'
```

Which is usually not how salt is used; 

Typically salt is used to prevent the construction of [rainbow tables](https://en.wikipedia.org/wiki/Rainbow_table), and make sure that if two users have the same pwd; their hashes are different.  But the system that hashes the password must have a stable salt for a given user !

Usually you have a table (user_id, salt, hash), and you regenerate the salt when the user sets, (or change) their password, and on login you:

 - get `hash, salt` for `user_id`,  compute `hashed(salt, pwd) == hash` and continue.

You _could_ use user_id, or username as salt; but as these are generally guessable or externally available, they are frowned upon.

**Comment by emilienschultz** [comment]
I understand, but in this case it seems the salt is stored in the hash, and I only use once to generate the hash when the user create a password, so it seems ok https://stackoverflow.com/questions/69175990/how-does-password-checking-in-bcrypt-work

**Comment by Carreau** [comment]
Ah fair. THanks.
