### ISSUE TITLE
Implement Quanteda DFM options in Python

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/activetigger#2]
Quanteda in R has more options for dfm than sklearn models : https://quanteda.io/reference/dfm_tfidf.html

- what are the most usefull options ?

**Comment by jboelaert** [comment]
You mean the tf-idf options, right?

The two important ones are:
- scheme_tf (details https://quanteda.io/reference/dfm_weight.html) : most important ones "count", "prop", "logcount", "boolean" (default "logcount")
- scheme_df (details https://quanteda.io/reference/docfreq.html) : most important "count", "inverse" (default "inverse")

The logarithmic base is unimportant, can be 2 or 10 or e (natural log), depending on the implementations.

**Comment by emilienschultz** [comment]
I don't think those tfidf options are available in sklearn https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html 

For the moment I will focus on available models and then implement those methods (or look for something elsewhere than sklearn) and check their implementation.

**Comment by jboelaert** [comment]
Sure. We don't need to get too fancy, sklearn's options are probably enough.
